server:
 port: 8080
 error:
  include-binding-errors: always
  include-message: always
  include-stacktrace: never
  
spring: 
 main:
  allow-circular-references: true # 8 ve 9 yeni eklendi
 jackson: 
  serialization: 
   write-dates-as-timestamps: false
 datasource:
  url: jdbc:postgresql://localhost:5432/furkanVakfiChat
  username: furkanVakfi
  password: aylaadem233
  driver-class-name: org.postgresql.Driver
 jpa:
  hibernate: 
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
   '[hibernate.format_sql]': true
  #image
 servlet:
  multipart:
   max-file-size: 2MB
   max-request-size: 2MB
 mail:
  host: smtp.gmail.com
  port: 587
  username: Example@gmail.com
  password: ExamplePassword
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true
#actuator deneme 
management: 
 endpoints:
  web:
   exposure:
    include: '*'
 info:
  env:
   enabled: true
 endpoint:
  health:
   show-details: always
  shutdown:
   enabled: true
   
   # secretkey
furkanVakfiChat :
 app :
  SECRETKEY : visionRent@!23 #furkanVakfiChat@!Aylaadem233
  JwtExpirationMs : 86400000 #bu rakam bir gune tekabul ediyor yani 24saat/milisanie


info:
 application:
  name: 'Daily Tasks Backend App'
  description: 'This is a Daily Tasks Program Backend Project'
  version: '@project.version@'    
   
